"""GRPO training driver for the defender LLM.

The defender is the only learner. The attack is not a policy: it is the
deterministic, detection-adaptive label-flip ladder in
:mod:`agents.label_flip_attacker`, run by the env. Each round it flips some
fraction of the insider clients' labels, the defender classifies every client
from weight-delta statistics, and the ladder reacts — backing the poison off a
step when the defender catches it, holding when it does not, resetting to full
strength once it bottoms out.

So there is still an arms race; it just is not two learners. The curriculum the
defender faces is generated by its own performance, which is what a fixed poison
rate cannot do: catch everything and the attack gets quieter and harder, miss and
it stays loud until you catch it.

**Phases.** A phase runs until the defender sustains a win (``success_streak``
consecutive rounds catching every poisoned client without over-flagging honest
ones) or hits ``max_phase_rounds``. On a phase boundary the defender adapter is
snapshotted into the league and persisted — one checkpoint per attack level it
has actually mastered — and, in a continuing federation, one honest FL round is
run between phases (``rl.fl_interlude_between_phases``).

**League.** Snapshots exist so the run keeps a history of defender checkpoints
to persist and inspect; with no opponent policy left there is nothing to swap
them into, so they are no longer played against.
"""

import logging

from core.types import RoundLog
from core.debug import dbg
from rl.grpo import grpo_step
from rl.rewards import (
    DEFAULT_ADVANTAGE_STD_FLOOR, DEFAULT_MIN_REWARD_SPREAD,
    attack_effectiveness, defender_reward,
)
from rl.switch import (
    PhaseController, SwitchConfig, attack_was_damaging, defender_succeeded,
    success_drop_bar,
)
from rl.turns import DefenderTurn

logger = logging.getLogger(__name__)


class League:
    """Bounded in-memory pool of past defender snapshots (CPU LoRA state dicts).

    Each snapshot is a full copy of the adapter's LoRA tensors — for the default
    Qwen2.5-3B + ``lora_r: 16`` over 7 projections × 36 layers that is ~30M
    parameters, i.e. **~115 MB per snapshot** in fp32. The pool was previously
    unbounded, so a long run grew it without limit and eventually OOM'd the box.

    It is now a ring buffer of at most ``max_snapshots``: once full, the OLDEST
    snapshot is dropped, giving a fixed memory ceiling of
    ``max_snapshots × ~115 MB``.
    """

    def __init__(self, rng, max_snapshots: int = 10):
        self.rng = rng
        self.max_snapshots = max(1, int(max_snapshots))
        self.snapshots: dict[str, list[dict]] = {}

    def snapshot(self, policy, names):
        """Append a snapshot of each named adapter, evicting the oldest past the cap."""
        evicted = 0
        for name in names:
            pool = self.snapshots.setdefault(name, [])
            pool.append(policy.get_adapter_state(name))
            while len(pool) > self.max_snapshots:
                pool.pop(0)          # ring buffer: drop the oldest
                evicted += 1
        logger.info(f"League: snapshotted {list(names)} "
                    f"(sizes={ {k: len(v) for k, v in self.snapshots.items()} }, "
                    f"cap={self.max_snapshots}, evicted={evicted})")

    def has(self, name) -> bool:
        return bool(self.snapshots.get(name))

    def sample(self, name) -> dict:
        return self.rng.choice(self.snapshots[name])


def resolve_round_budget(configured: int, total_rounds=None, max_new_rounds=None,
                         start_round: int = 0) -> int:
    """Absolute round budget for this run (the loop runs while ``done < budget``).

    * ``total_rounds`` (``main.py --rounds N``) replaces ``fl.simulation_rounds``
      as the ABSOLUTE budget — matching what ``--rounds`` documents, so a resumed
      run counts the rounds it already did toward N.
    * ``max_new_rounds`` (``main.py --debug``) additionally caps how many rounds
      THIS invocation may add on top of ``start_round``, so a short debug run still
      executes rounds when resuming a long training run.
    """
    budget = int(configured if total_rounds is None else total_rounds)
    if max_new_rounds is not None:
        budget = min(budget, int(start_round) + int(max_new_rounds))
    return budget


def _curriculum_slot(env) -> dict | None:
    """This round's curriculum block as a log-friendly dict, or ``None`` when the
    run has no curriculum."""
    slot = getattr(env, "round_curriculum", None)
    return slot.as_log_dict() if slot is not None else None


def _resume_curriculum(env, resume: dict | None, start_round: int) -> None:
    """Put the defense sweep back where it stopped.

    Prefer the saved ``curriculum`` snapshot. Older progress files predate it, so
    fall back to ``start_round``: the curriculum advances exactly once per
    committed GRPO round (``begin_round``) and ``rounds_done`` counts exactly
    those rounds — the FL interlude between phases advances neither — so the two
    counters are the same number.
    """
    curriculum = getattr(env, "curriculum", None)
    if curriculum is None:
        return
    saved = (resume or {}).get("curriculum")
    if saved:
        curriculum.load_state_dict(saved)
    elif start_round:
        curriculum.load_state_dict({"step": int(start_round)})
        logger.info(
            f"No saved curriculum position (older checkpoint) — deriving it from "
            f"rounds_done={start_round}, which counts the same rounds."
        )
    slot = curriculum.peek()
    logger.info(
        f"Curriculum resumes at step {curriculum.step}: block {slot.block} "
        f"(cycle {slot.cycle}, {slot.position + 1}/{curriculum.blocks_per_cycle}) "
        f"round {slot.block_round + 1}/{curriculum.rounds_per_block} — "
        f"defense={slot.algorithm or 'llm'}"
    )


def _argmax(xs: list[float]) -> int:
    best, bi = xs[0], 0
    for i, x in enumerate(xs):
        if x > best:
            best, bi = x, i
    return bi


def _committed_index(rewards: list[float], mode: str, rng) -> int:
    """Which of the G scored rollouts actually advances the environment.

    ``sample`` (default) — a uniformly random member of the group, i.e. a genuine
    draw from the policy. ``argmax`` — the best-scoring one (the legacy behaviour).

    Committing the argmax is a best-of-G evaluation dressed up as a policy rollout,
    and here it would corrupt the attack schedule as well as the metrics: the
    LADDER reacts to the committed round's verdicts, so committing the best-of-G
    verdict would step the poison down on detections the policy does not reliably
    produce, and the defender would then be trained against an attack calibrated to
    its luckiest sample rather than its actual behaviour.

    It also makes the phase gate honest — ``rl/switch.py`` counts a win on the
    committed round — and keeps the state trajectory on-policy. The argmax is still
    recorded (``best_index``) so the gap between the two is visible in the logs.
    """
    if not rewards:
        return 0
    if str(mode).lower() == "argmax":
        return _argmax(rewards)
    return rng.randrange(len(rewards))


def train(
    env,
    policy,
    defender_agent,
    cfg: dict,
    metrics_tracker,
    save_round_log,
    rng,
    progress_cb=None,
    fl_state_cb=None,
    start_round: int = 0,
    resume: dict | None = None,
    total_rounds: int | None = None,
    max_new_rounds: int | None = None,
):
    """Run the defender's GRPO training loop over ``simulation_rounds`` rounds.

    ``resume`` is the dict from ``storage.load_progress`` — ``rounds_done`` (also
    passed as ``start_round``), plus, for a full resume, the saved FL ``round_index``
    (so round numbering/logs continue), the ``controller`` snapshot (so the phase
    schedule continues) and the ``attacker`` snapshot (so the label-flip ladder
    resumes at the level it had reached rather than restarting at full poison).

    ``total_rounds`` overrides ``fl.simulation_rounds`` as the ABSOLUTE round
    budget (``main.py --rounds N``); ``max_new_rounds`` caps how many rounds THIS
    invocation may add on top of ``start_round`` (``main.py --debug``).
    """
    if getattr(env, "defense", None) is not None:
        raise RuntimeError(
            "Training needs the defender LLM, but this run defends with algorithms "
            "(defense.mode: algorithmic). The attack is a fixed label-flip schedule, "
            "so with an algorithmic defense there is no policy left to train. Set "
            "defense.mode: llm to train the defender, or use --dry-run / --baseline "
            "to just run the round loop."
        )

    rl = cfg.get("rl", {})
    G = int(rl.get("G", 4))
    kl_beta = float(rl.get("kl_beta", 0.02))
    lr = float(rl.get("lr", 1e-5))
    learner_temp = float(rl.get("temperature", 1.0))
    max_new_tokens = int(rl.get("max_new_tokens", 2048))
    grad_clip = float(rl.get("grad_clip", 1.0))
    save_every = int(rl.get("save_every", 50))
    snap_every = int(rl.get("league_snapshot_every", 100))
    league_max = int(rl.get("league_max_snapshots", 10))
    skip_zero_adv = bool(rl.get("skip_zero_advantage", True))
    resample_zero_adv = bool(rl.get("resample_on_zero_advantage", True))
    resample_temp = float(rl.get("resample_temperature", 1.3))
    min_reward_spread = float(rl.get("min_reward_spread", DEFAULT_MIN_REWARD_SPREAD))
    advantage_std_floor = float(rl.get("advantage_std_floor", DEFAULT_ADVANTAGE_STD_FLOOR))
    commit_selection = str(rl.get("commit_selection", "sample")).lower()
    if commit_selection not in ("sample", "argmax"):
        raise ValueError(f"rl.commit_selection must be sample|argmax, got {commit_selection!r}")
    fl_interlude = bool(rl.get("fl_interlude_between_phases", True))
    adapter_paths = rl.get("adapter_paths", {"defender": "checkpoints/defender_adapter"})
    reward_def = rl.get("reward", {}).get("defender", {})
    switch_cfg = SwitchConfig.from_cfg(rl)

    total_rounds = resolve_round_budget(
        int(cfg["fl"]["simulation_rounds"]), total_rounds, max_new_rounds, start_round)
    if start_round >= total_rounds:
        logger.warning(
            f"Nothing to do: {start_round} round(s) already done and the budget is "
            f"{total_rounds}. Raise fl.simulation_rounds or pass a larger --rounds."
        )
    else:
        logger.info(f"Training budget: rounds {start_round} -> {total_rounds}")
    logger.info(f"Defender-only GRPO against {env.attacker.describe()}")

    import torch
    trainable = ("defender",)
    optimizers = {
        name: torch.optim.AdamW(policy.adapter_parameters(name), lr=lr)
        for name in trainable
    }
    league = League(rng, max_snapshots=league_max)

    # Per-round knobs bundled so the round body reads as one call.
    knobs = dict(
        G=G, kl_beta=kl_beta, learner_temp=learner_temp, max_new_tokens=max_new_tokens,
        grad_clip=grad_clip, skip_zero_adv=skip_zero_adv,
        resample_zero_adv=resample_zero_adv, resample_temp=resample_temp,
        reward_def=reward_def, min_reward_spread=min_reward_spread,
        advantage_std_floor=advantage_std_floor, commit_selection=commit_selection,
    )

    state = dict(
        env=env, policy=policy, defender_agent=defender_agent,
        optimizers=optimizers, league=league, knobs=knobs, switch_cfg=switch_cfg,
        metrics_tracker=metrics_tracker, save_round_log=save_round_log,
        adapter_paths=adapter_paths, progress_cb=progress_cb, total_rounds=total_rounds,
        save_every=save_every, snap_every=snap_every,
        max_new_tokens=max_new_tokens, rng=rng, fl_interlude=fl_interlude,
        controller=None, fl_state_cb=fl_state_cb, trainable=trainable,
    )

    # Resume the FL round-number counter so round labels + logs/round_data advance
    # across restarts instead of overwriting from the first Phase-2 round. Prefer the
    # saved round_index; fall back to start_round for old progress files that only
    # stored rounds_done. (env.reset() zeroed round_index just before this.)
    if resume and resume.get("round_index") is not None:
        env.round_index = int(resume["round_index"])
    elif start_round:
        env.round_index = int(start_round)

    # The ladder is part of the run's state: restarting it at full poison after a
    # crash would replay attack levels the defender has already been trained past.
    if resume and resume.get("attacker"):
        env.attacker.load_state_dict(resume["attacker"])

    _resume_curriculum(env, resume, start_round)

    logger.info(
        f"Schedule: defender phases (streak={switch_cfg.success_streak}, "
        f"min/max phase={switch_cfg.min_phase_rounds}/{switch_cfg.max_phase_rounds})"
    )
    done = _train_defender(state, start_round, resume=resume)

    _checkpoint(state, done)   # final save
    logger.info(f"Training complete — {done} rounds. Adapter saved to {adapter_paths}")


def _step_round(state, phase_index, phase_round):
    """Run ONE committed GRPO round for the defender.

    Returns ``(stats, committed_drop, success)`` where ``committed_drop`` is the
    accuracy the round's flipped labels cost against the clean counterfactual and
    ``success`` is whether the defender won this round.
    """
    env = state["env"]
    k = state["knobs"]
    ctx = env.begin_round()

    dbg.round_header(ctx.round_num, "defender", phase_index, phase_round,
                     ctx.poisoned_ids, ctx.flip_fraction, ctx.flip_plan,
                     ctx.global_accuracy, k["G"], curriculum=_curriculum_slot(env))
    dbg.fl_round(ctx.round_num, ctx.poisoned_ids, env.build_updates(),
                 env.current_accuracy)

    turn = DefenderTurn(env, state["defender_agent"], reward_cfg=k["reward_def"])

    stats = grpo_step(
        state["policy"], "defender", state["optimizers"]["defender"], turn,
        G=k["G"], kl_beta=k["kl_beta"], temperature=k["learner_temp"],
        max_new_tokens=k["max_new_tokens"], grad_clip=k["grad_clip"],
        skip_zero_advantage=k["skip_zero_adv"],
        resample_on_zero_advantage=k["resample_zero_adv"],
        resample_temperature=k["resample_temp"],
        min_reward_spread=k["min_reward_spread"],
        advantage_std_floor=k["advantage_std_floor"],
    )

    # Advance the env with an ON-POLICY draw from the group (see _committed_index):
    # this round's verdicts also drive the attack ladder, so committing the argmax
    # would calibrate the next round's poison to the policy's luckiest sample.
    best = _argmax(stats["rewards"]) if stats["rewards"] else 0
    committed = _committed_index(stats["rewards"], k["commit_selection"], state["rng"])
    info = turn.commit(stats["completions"][committed])

    # Damage vs THIS round's clean counterfactual (what the aggregate would have
    # scored with the same clients trained on their real labels).
    drop = ctx.clean_accuracy - info["post_accuracy"]
    success = defender_succeeded(info["verdicts"], ctx.poisoned_ids, state["switch_cfg"])

    # The damage bar this round's attack is reported against, shared with the metrics
    # tracker so the recorded attack_success means the same thing everywhere.
    success_drop = success_drop_bar(ctx.goal, state["switch_cfg"])

    _log_round(env, ctx, info, stats, state["metrics_tracker"],
               state["save_round_log"], reward_def=k["reward_def"],
               phase_index=phase_index, phase_round=phase_round, success=success,
               best_index=best, committed_index=committed,
               defense_algorithm=env.round_defense, success_drop=success_drop,
               switch_cfg=state["switch_cfg"])
    return stats, drop, success


def _post_round_bookkeeping(state, done):
    """League snapshots + checkpoints on the configured cadence."""
    if state["snap_every"] and done % state["snap_every"] == 0:
        state["league"].snapshot(state["policy"], state["trainable"])
    # Checkpoint adapters + progress TOGETHER so a resume is always consistent
    # (the saved round count never points past the saved adapter weights).
    if state["save_every"] and done % state["save_every"] == 0:
        _checkpoint(state, done)


def _run_fl_interlude(state, phase_index):
    """Between two defender phases, advance the shared FL state by one honest
    FedAvg round (exactly like a Phase-1 round) and log it.

    Skipped entirely under ``fl.freeze_global_in_phase2`` (the default), where
    every round branches off the frozen anchor and there is no shared FL state to
    advance — see ``FLArmsRaceEnv.run_benign_fl_round``.
    """
    env = state["env"]
    info = env.run_benign_fl_round()
    if info is None:
        return
    round_num = info["round_num"]
    updates = info["updates"]

    dbg.phase_event("FL ROUND (interlude)", round=round_num, phase=phase_index,
                    prev_acc=round(info["prev_accuracy"], 4),
                    post_acc=round(info["post_accuracy"], 4))
    dbg.fl_round(round_num, [], updates, info["post_accuracy"])
    dbg.flush()

    # Persist a round log so the interlude shows up in logs/round_data/rounds.jsonl.
    state["save_round_log"](RoundLog(
        round_num=round_num,
        attack_goal=env.goal,
        poisoned_client_ids=[],
        predicted_labels=[],
        test_accuracy=info["post_accuracy"],
        baseline_accuracy=env.baseline_accuracy,
        attack_effectiveness=0.0,
        defender_reward=0.0,
        learning_agent="none",
        attack_metadata={
            "event": "benign_fl_round",
            "phase_index": phase_index,
            "prev_accuracy": info["prev_accuracy"],
            "post_accuracy": info["post_accuracy"],
            "n_clients": info["n_clients"],
            "clients": [
                {"client_id": u.client_id, **(u.metadata or {})} for u in updates
            ],
        },
    ))
    logger.info(
        f"[FL round {round_num}] interlude before phase {phase_index}: "
        f"acc {info['prev_accuracy']:.4f} -> {info['post_accuracy']:.4f} "
        f"— new benign client weights now consumed by the attack and the aggregator"
    )


def _train_defender(state, start_round, resume=None):
    """Run defender phases until the round budget is spent. Returns the round count."""
    ctrl = PhaseController(state["switch_cfg"], first_learner="defender",
                           learners=state["trainable"])
    if resume and resume.get("controller"):
        ctrl.load_state_dict(resume["controller"])
        logger.info(
            f"Resumed schedule state: phase={ctrl.phase_index} "
            f"phase_round={ctrl.phase_round} streak={ctrl.streak} capped={ctrl.capped}"
        )
    state["controller"] = ctrl   # exposed so _checkpoint can persist it
    done = start_round

    while done < state["total_rounds"]:
        # Before every phase AFTER the first, run one honest FL round so the next
        # phase trains against a freshly advanced client state (mirrors a Phase-1
        # round). Gated on phase_round == 0 so it fires only at a TRUE phase start —
        # NOT when resuming into the middle of a phase, which would otherwise inject
        # a spurious benign round on every restart.
        if (ctrl.phase_index > 0 and ctrl.phase_round == 0
                and state.get("fl_interlude", True)):
            _run_fl_interlude(state, phase_index=ctrl.phase_index)
        dbg.phase_event("PHASE START", phase=ctrl.phase_index, learner="defender")

        reason = None
        while done < state["total_rounds"]:
            _stats, _drop, success = _step_round(state, ctrl.phase_index, ctrl.phase_round)
            done += 1
            # Record the round on the controller FIRST, then checkpoint — so the
            # persisted controller state (phase_round/streak) and rounds_done refer
            # to the SAME completed round.
            switch, reason = ctrl.record(success)
            _post_round_bookkeeping(state, done)
            if switch:
                break

        # Freeze the defender at this phase's checkpoint: snapshot it into the
        # league and persist its adapter.
        state["league"].snapshot(state["policy"], ["defender"])
        state["policy"].save_adapter("defender", state["adapter_paths"]["defender"])
        logger.info(
            f"Phase {ctrl.phase_index} [defender] ended ({reason or 'budget'}) "
            f"after {ctrl.phase_round} rounds (streak={ctrl.streak}) — froze defender"
        )
        dbg.phase_event("PHASE END", phase=ctrl.phase_index, learner="defender",
                        reason=reason or "budget", rounds=ctrl.phase_round,
                        streak=ctrl.streak)
        if reason is None:   # ran out of total budget mid-phase
            break
        ctrl.next_phase(reason)
        # Persist the just-completed phase boundary so a crash right after it
        # resumes in the NEW phase instead of re-running the finished one.
        _checkpoint(state, done)

    return done


def _checkpoint(state, done):
    """Save the adapter + the shared FL state, then the resume state (round count,
    FL round index, the PhaseController snapshot, the label-flip ladder position and
    the curriculum's position) so a resume is always consistent — the saved round
    count never points past the saved weights, the shared model continues instead of
    rewinding to the Phase-1 baseline, and the attack resumes at the ladder level it
    had actually reached."""
    policy = state["policy"]
    for name in state["trainable"]:
        policy.save_adapter(name, state["adapter_paths"][name])
    if state.get("fl_state_cb"):
        state["fl_state_cb"](state["env"].snapshot_fl_state())
    if state["progress_cb"]:
        ctrl = state.get("controller")
        env = state["env"]
        cur = getattr(env, "curriculum", None)
        state["progress_cb"](done, env.round_index,
                             ctrl.state_dict() if ctrl is not None else None,
                             cur.state_dict() if cur is not None else None,
                             env.attacker.state_dict())


def _warn_defense_malfunction(round_num, defense_algorithm, verdicts, poisoned_ids):
    """Shout when the round's defense behaved in a way that invalidates the numbers.

    A defense that rejects the honest majority is not "a hard round for the attack" —
    every quantity derived from that round is meaningless: the clean counterfactual,
    the post-attack accuracy, the drop. The symptoms all look like ordinary numbers
    (an accuracy, a small drop), which is why this is checked explicitly.

    The loudest case is a strict subset accept: the defense dropping all the honest
    clients and keeping ONLY the poisoned one, so the "defended" aggregate is built
    purely from the attack.
    """
    if not verdicts:
        return
    accepted = [v.client_id for v in verdicts if not v.is_suspicious]
    poisoned = set(poisoned_ids or ())
    tag = f"Round {round_num} [{defense_algorithm or 'llm'}]"
    if not accepted:
        logger.warning("%s: defense REJECTED ALL %d clients — no aggregate is possible "
                       "and this round's accuracy carries no information",
                       tag, len(verdicts))
        return
    if poisoned and set(accepted) <= poisoned:
        logger.warning(
            "%s: defense accepted ONLY POISONED clients (%s of %d) — the aggregate is "
            "built entirely from the attack, so the measured drop reflects a defense "
            "malfunction", tag, sorted(accepted), len(verdicts))
        return
    honest_total = len(verdicts) - len(poisoned)
    honest_rejected = honest_total - len([c for c in accepted if c not in poisoned])
    if honest_total > 0 and honest_rejected > honest_total / 2:
        logger.warning(
            "%s: defense rejected %d of %d HONEST clients (FPR=%.2f) — dropping the "
            "honest majority indicates a miscalibrated defense, not a strong attack",
            tag, honest_rejected, honest_total, honest_rejected / honest_total)


def _log_round(env, ctx, info, stats, metrics_tracker, save_round_log,
               reward_def=None, phase_index=0, phase_round=0, success=False,
               best_index=0, committed_index=0, defense_algorithm=None,
               success_drop=None, switch_cfg=None):
    verdicts = info["verdicts"]
    post_acc = info["post_accuracy"]
    poisoned_ids = ctx.poisoned_ids
    reward_def = reward_def or {}
    goal = ctx.goal if getattr(ctx, "goal", None) is not None else env.goal

    d_rew = defender_reward(verdicts, poisoned_ids,
                            mode=reward_def.get("mode", "soft_f1"),
                            fpr_penalty=reward_def.get("fpr_penalty", 1.0))
    drop = ctx.clean_accuracy - post_acc
    # How hard the round's flipped labels actually hit the model, on the goal's
    # scale. Reported, never trained on — see rl.rewards.attack_effectiveness.
    effectiveness = attack_effectiveness(ctx.clean_accuracy, post_acc, goal)
    damaging = attack_was_damaging(drop, poisoned_ids, switch_cfg or SwitchConfig(), goal)

    clean_measured = bool(getattr(ctx, "clean_measured", True))
    defense_sane = bool(getattr(ctx, "defense_sane", True))
    _warn_defense_malfunction(ctx.round_num, defense_algorithm, verdicts, poisoned_ids)

    # ``clean_accuracy`` is passed only when it was really measured AND measured
    # through a defense that was working: the tracker derives the damage-based
    # attack_success from it, and must treat neither the current-global fallback
    # (clean_measured=False) nor a counterfactual built after the honest majority
    # was rejected (defense_sane=False) as a counterfactual.
    countable = clean_measured and defense_sane
    metrics_tracker.update(ctx.round_num, verdicts, post_acc, set(poisoned_ids),
                           clean_accuracy=(ctx.clean_accuracy if countable else None),
                           success_drop=success_drop)
    ladder = info.get("ladder") or {}
    save_round_log(RoundLog(
        round_num=ctx.round_num,
        attack_goal=goal,
        poisoned_client_ids=list(poisoned_ids),
        predicted_labels=[
            {"client_id": v.client_id, "is_suspicious": v.is_suspicious,
             "confidence": v.confidence, "reason": v.reason}
            for v in verdicts
        ],
        test_accuracy=post_acc,
        baseline_accuracy=env.baseline_accuracy,
        attack_effectiveness=effectiveness,
        defender_reward=d_rew,
        learning_agent="defender",
        attack_metadata={
            "attack": "label_flip",
            # The ladder level this round was SENT at, and how many labels that
            # meant per client — the two numbers that describe the attack.
            "flip_fraction": round(float(ctx.flip_fraction), 6),
            "flip_plan": {str(cid): n for cid, n in sorted(ctx.flip_plan.items())},
            "n_flipped": sum(ctx.flip_plan.values()),
            "n_poisoned": len(poisoned_ids),
            # Where the ladder moved after seeing this round's verdicts: whether the
            # defense caught it, and whether that held, stepped down, or reset the
            # cycle. This is the run's attack schedule, recoverable from its own logs.
            "ladder": ladder,
            # Which defense faced this round: "llm" while the defender LLM is in
            # charge, else the algorithm name. Rounds are only comparable within one.
            "defense": defense_algorithm or "llm",
            "curriculum": _curriculum_slot(env),
            # The clean counterfactual and the damage measured against it — the same
            # clients, same data, real labels — so the drop isolates the flipped
            # labels rather than round-to-round drift.
            "clean_accuracy": round(float(ctx.clean_accuracy), 6),
            "induced_drop": round(float(drop), 6),
            # Normalized damage on the goal's scale (1.0 = hit target_accuracy_drop),
            # and whether it cleared the reporting bar.
            "attack_effectiveness": round(float(effectiveness), 6),
            "attack_damaging": damaging,
            # False = the defense produced no clean aggregate, so `clean_accuracy` is
            # the current global's accuracy standing in for a counterfactual that does
            # not exist and `induced_drop` is not a measurement. Slice these rounds OUT
            # before reporting damage.
            "clean_measured": clean_measured,
            # False = the round's defense had already rejected the honest majority of
            # the UNPOISONED cohort, so `clean_accuracy` / `induced_drop` measure its
            # false-positive rate rather than the attack. Slice these out too.
            "defense_sane": defense_sane,
            "phase_index": phase_index,
            "phase_round": phase_round,
            "learner_success": success,
            "train": {
                "loss": stats["loss"],
                "mean_reward": stats["mean_reward"],
                "max_reward": stats["max_reward"],
                # Raw within-group reward span: the quantity the degeneracy gate
                # tests, so a run of skipped steps is diagnosable from the logs.
                "reward_spread": stats.get("reward_spread"),
                # Which rollout advanced the env vs which scored best. They differ by
                # design (an on-policy draw, not best-of-G), so the gap is the honest
                # measure of how optimistic an argmax commit would have been.
                "committed_index": committed_index,
                "best_index": best_index,
                "committed_reward": (stats["rewards"][committed_index]
                                     if stats["rewards"] else None),
                "total_tokens": stats.get("total_tokens"),
                "completion_tokens": stats.get("completion_tokens"),
                "zero_advantage_fraction": stats["zero_advantage_fraction"],
                # Degeneracy of the FIRST draw, before any re-roll. The field above is
                # post-resample, so on its own it reports a healthy group for a round
                # that only became healthy on the second attempt.
                "zero_advantage_fraction_first_draw":
                    stats.get("zero_advantage_fraction_first_draw"),
                "stepped": stats.get("stepped", True),
                "resampled": stats.get("resampled", False),
            },
        },
    ))
    dbg.commit_summary(
        "defender", committed_index, info, ctx.clean_accuracy, post_acc, drop,
        success, effectiveness, d_rew, poisoned_ids,
        global_acc=ctx.global_accuracy, best_index=best_index, ladder=ladder,
    )
    dbg.flush()
    slot = getattr(env, "round_curriculum", None)
    # ph / blk are "index/round" pairs, NOT decimals: `ph=0/14` is phase 0 round 14.
    logger.info(
        f"Round {ctx.round_num} [ph={phase_index}/{phase_round} "
        f"def={defense_algorithm or 'llm'} "
        + (f"blk={slot.block}/{slot.block_round} " if slot else "")
        + f"{'WIN' if success else '...'}]: "
        f"flip={ctx.flip_fraction:.0%}({sum(ctx.flip_plan.values())} labels) "
        f"acc {ctx.global_accuracy:.4f}->{post_acc:.4f} "
        f"(clean_ref={ctx.clean_accuracy:.4f}{'' if clean_measured else '~UNMEASURED'} "
        f"drop={drop:+.4f} eff={effectiveness:+.2f}) "
        f"| def_reward={d_rew:.3f} ladder={ladder.get('event', '-')}"
        f"->{ladder.get('next_flip_fraction', ctx.flip_fraction):.0%} "
        f"| grpo_loss={stats['loss']:.4f} mean_r={stats['mean_reward']:.3f} "
        f"spread={stats.get('reward_spread', 0.0):.3f} "
        f"zero_adv={stats['zero_advantage_fraction']:.2f}"
        f"(first={stats.get('zero_advantage_fraction_first_draw', 0.0):.2f}) "
        + ("resampled " if stats.get("resampled") else "")
        + ("step" if stats.get("stepped", True) else "SKIP-degenerate")
    )
