"""The attacker: a deterministic, detection-adaptive label-flipping schedule.

There is no attacker LLM and no attacker policy. The adversary is a fixed set of
insider clients plus one scalar — how much of their local data carries a flipped
label this round — driven by a feedback ladder that reacts to whether the defense
caught the last round.

THE LADDER
----------
Start at the top: flip EVERY example the poisoned client trains on this round.

* **Caught** -> step down one level (10% of the client's data by default), i.e.
  1000 -> 900 -> 800 -> ... on a client holding 1000 examples. The attack backs
  off, probing for the largest poison the defense still misses.
* **Not caught** -> HOLD. The current level is working, so it is sent again,
  unchanged, for as many rounds as it keeps working.
* **Caught at the floor** -> RESET to the top and start the descent again.

The floor (50% by default) exists because a label-flip attack that only
mislabels a small minority of a client's data stops being an attack: the honest
gradient dominates, the update is indistinguishable from noise, and neither
"caught" nor "missed" carries information. The reset exists so the run does not
park at the floor forever once it gets there — the defender must keep proving
itself against the full range of attack strengths, round after round, rather
than being trained on one static setting for the rest of the run.

So a run sweeps a saw-tooth in attack strength whose descent rate is set by the
DEFENDER's own competence: a defender that catches everything drives the ladder
to the floor and back to the top every ``levels`` rounds, while a weak defender
leaves it parked at a high level. That coupling is the point — the curriculum the
defender trains against is generated by its own failures, which is exactly the
adversarial pressure a fixed poison rate cannot provide.

The ladder is a pure function of its level counter, and the counter advances
exactly once per committed simulation round, so the whole schedule is
reproducible and is checkpointed with the rest of the Phase-2 resume state.

WHAT "CAUGHT" MEANS
-------------------
``caught_rule`` decides, when several clients are poisoned, how many of them the
defense must flag for the round to count as caught. The default is ``all``: the
attack is only considered detected when the defense catches every poisoned
client, so one surviving insider is a successful round and the ladder holds.
"""

import logging

logger = logging.getLogger(__name__)

#: How many of the poisoned clients the defense must flag for the round to count
#: as "caught" (and so step the ladder down).
CAUGHT_RULES = ("all", "any", "majority")

DEFAULT_START_FRACTION = 1.0
DEFAULT_STEP_FRACTION = 0.1
DEFAULT_FLOOR_FRACTION = 0.5


class FlipLadder:
    """The detection-adaptive flip-count schedule (see the module docstring).

    Levels are held as an INTEGER index rather than a running float subtraction:
    ``fraction = start - level * step``. Repeatedly doing ``f -= 0.1`` from 1.0
    lands on 0.7999999999999999 and 0.5000000000000001, so the floor comparison
    that decides when to reset would be at the mercy of binary rounding. With an
    index the level set is exact and finite, and "at the floor" is just
    ``level == n_levels - 1``.
    """

    def __init__(self, start: float = DEFAULT_START_FRACTION,
                 step: float = DEFAULT_STEP_FRACTION,
                 floor: float = DEFAULT_FLOOR_FRACTION):
        start = float(start)
        step = float(step)
        floor = float(floor)
        if not 0.0 < start <= 1.0:
            raise ValueError(f"attack.schedule.start_fraction must be in (0, 1], got {start}")
        if step <= 0.0:
            raise ValueError(f"attack.schedule.step_fraction must be > 0, got {step}")
        if not 0.0 <= floor <= start:
            raise ValueError(
                f"attack.schedule.floor_fraction must be in [0, start_fraction={start}], "
                f"got {floor}"
            )
        self.start = start
        self.step = step
        # Snap the floor onto the step grid: with start=1.0 and step=0.1 a floor of
        # 0.55 is not reachable by stepping, and silently descending past it would
        # break the "stops dropping at the floor" contract. The reachable level at
        # or above the requested floor is used instead, and the difference is logged.
        self.n_levels = max(1, int((start - floor) / step + 1e-9) + 1)
        self.floor = self.fraction_at(self.n_levels - 1)
        if abs(self.floor - floor) > 1e-9:
            logger.info(
                f"Flip ladder: floor {floor:g} is not on the {step:g} step grid from "
                f"{start:g} — using the nearest reachable level {self.floor:g}."
            )
        self.level = 0            # 0 = the top (start fraction)
        self.cycle = 0            # completed top->floor->reset descents
        self.rounds_at_level = 0  # consecutive rounds spent at the current level

    # ------------------------------------------------------------------
    def fraction_at(self, level: int) -> float:
        """The flip fraction at ``level``, rounded off binary-representation dust."""
        level = max(0, min(int(level), self.n_levels - 1))
        return round(self.start - level * self.step, 10)

    @property
    def fraction(self) -> float:
        """This round's flip fraction — the share of a poisoned client's local data
        whose labels are flipped."""
        return self.fraction_at(self.level)

    @property
    def at_floor(self) -> bool:
        return self.level >= self.n_levels - 1

    def levels(self) -> list[float]:
        """Every fraction the ladder visits, top to floor."""
        return [self.fraction_at(i) for i in range(self.n_levels)]

    # ------------------------------------------------------------------
    def advance(self, caught: bool) -> str:
        """Apply one round's outcome. Returns the transition that happened:
        ``"hold"``, ``"step_down"`` or ``"reset"``.

        Called exactly once per COMMITTED round — never per scored rollout, which
        would let the number of GRPO samples change the attack schedule.
        """
        if not caught:
            self.rounds_at_level += 1
            return "hold"
        if self.at_floor:
            self.level = 0
            self.cycle += 1
            self.rounds_at_level = 0
            return "reset"
        self.level += 1
        self.rounds_at_level = 0
        return "step_down"

    # ------------------------------------------------------------------
    def state_dict(self) -> dict:
        """Serializable position, for resume. The GRID (start/step/floor) is saved
        alongside it so a config edit between runs is detectable rather than
        silently re-interpreting a saved level as a different fraction."""
        return {
            "level": self.level,
            "cycle": self.cycle,
            "rounds_at_level": self.rounds_at_level,
            "grid": {"start": self.start, "step": self.step, "n_levels": self.n_levels},
        }

    def load_state_dict(self, state: dict) -> None:
        grid = state.get("grid")
        now = {"start": self.start, "step": self.step, "n_levels": self.n_levels}
        if grid and grid != now:
            logger.warning(
                f"Flip ladder grid changed since the last run (saved={grid}, now={now}). "
                f"Keeping the saved level, which now maps to a DIFFERENT flip fraction."
            )
        self.level = max(0, min(int(state.get("level", self.level)), self.n_levels - 1))
        self.cycle = max(0, int(state.get("cycle", self.cycle)))
        self.rounds_at_level = max(0, int(state.get("rounds_at_level", self.rounds_at_level)))


class LabelFlipAttacker:
    """The whole adversary: which clients flip, how many labels, and the feedback.

    Stateless with respect to the FL round except for the ladder, so the env can
    ask it for a plan at the start of a round and hand it the verdicts at the end.
    """

    def __init__(self, config: dict | None = None, n_clients: int | None = None,
                 seed: int = 0):
        config = config or {}
        sched = config.get("schedule") or {}
        self.seed = int(seed)
        self.n_classes = int(config.get("n_classes", 10))
        self.ladder = FlipLadder(
            start=sched.get("start_fraction", DEFAULT_START_FRACTION),
            step=sched.get("step_fraction", DEFAULT_STEP_FRACTION),
            floor=sched.get("floor_fraction", DEFAULT_FLOOR_FRACTION),
        )
        rule = str(sched.get("caught_rule", "all")).lower()
        if rule not in CAUGHT_RULES:
            raise ValueError(f"attack.schedule.caught_rule must be one of "
                             f"{list(CAUGHT_RULES)}, got {rule!r}")
        self.caught_rule = rule
        self.poison_client_ids = self._resolve_clients(config, n_clients)

    # ------------------------------------------------------------------
    @staticmethod
    def _resolve_clients(config: dict, n_clients: int | None) -> list[int]:
        """Validate ``attack.poison_client_ids`` into a sorted, deduped id list.

        Defaults to ``[0]`` — a single insider, the first client. Ids outside the
        federation are dropped with a warning rather than clamped: clamping would
        quietly turn ``[0, 25]`` into two attacks on client 0 (or on whichever id
        the clamp lands on), which is not what the config asked for.
        """
        raw = config.get("poison_client_ids", [0])
        if isinstance(raw, int):
            raw = [raw]
        ids, seen = [], set()
        for item in raw or []:
            cid = int(item)
            if cid < 0 or (n_clients is not None and cid >= int(n_clients)):
                logger.warning(
                    f"attack.poison_client_ids: dropping client {cid} — outside "
                    f"0..{(int(n_clients) - 1) if n_clients is not None else '?'}"
                )
                continue
            if cid in seen:
                logger.warning(f"attack.poison_client_ids: dropping duplicate {cid}")
                continue
            ids.append(cid)
            seen.add(cid)
        if not ids:
            raise ValueError(
                "attack.poison_client_ids resolved to an empty set — list at least one "
                "valid client id (default: [0])"
            )
        return sorted(ids)

    # ------------------------------------------------------------------
    @property
    def fraction(self) -> float:
        return self.ladder.fraction

    def flip_seed(self, round_index: int, client_id: int) -> int:
        """Seed for WHICH examples client ``client_id`` flips in ``round_index``.

        Derived arithmetically from the run seed so it is stable across processes
        and independent of the ambient RNG — the same property
        ``data.round_sampler`` relies on, and for the same reason: a resumed run
        must reproduce the interrupted one's poison exactly.
        """
        return ((self.seed * 1_000_003 + int(client_id)) * 1_000_003
                + int(round_index)) & 0x7FFFFFFF

    def plan(self, sample_counts: dict[int, int]) -> dict[int, int]:
        """This round's flip count per poisoned client.

        ``sample_counts`` is ``{client_id: examples it trains on THIS round}`` —
        the per-round slice, not the whole shard, since that is the data the
        labels are actually flipped in. The ladder's fraction is applied to each
        client's own count, so a non-IID partition (which gives clients unequal
        shards) still flips the same PROPORTION everywhere.
        """
        frac = self.ladder.fraction
        plan = {}
        for cid in self.poison_client_ids:
            n = max(0, int(sample_counts.get(cid, 0)))
            plan[cid] = min(n, int(round(frac * n)))
        return plan

    # ------------------------------------------------------------------
    def caught(self, verdicts, poisoned_ids) -> bool:
        """Did the defense catch this round, under ``caught_rule``?

        ``poisoned_ids`` is the round's GROUND TRUTH (the clients that actually
        shipped flipped labels), not the configured set: a client whose ladder
        level rounded to zero flips sent an honest update, and holding the
        defense responsible for not flagging it would step the ladder on a
        detection that could not have happened.
        """
        ids = list(poisoned_ids or [])
        if not ids:
            return False
        flagged = {v.client_id for v in verdicts if v.is_suspicious}
        n_flagged = sum(1 for cid in ids if cid in flagged)
        if self.caught_rule == "any":
            return n_flagged > 0
        if self.caught_rule == "majority":
            return n_flagged * 2 > len(ids)
        return n_flagged == len(ids)

    def record_round(self, verdicts, poisoned_ids) -> dict:
        """Feed one COMMITTED round's verdicts back into the ladder.

        Returns a log-friendly record of the transition — the level the round was
        sent at, whether it was caught, and where the ladder moved to — which the
        round log carries so a run can be replayed from its own logs.
        """
        before = self.ladder.fraction
        caught = self.caught(verdicts, poisoned_ids)
        event = self.ladder.advance(caught)
        record = {
            "flip_fraction": before,
            "caught": caught,
            "caught_rule": self.caught_rule,
            "event": event,
            "next_flip_fraction": self.ladder.fraction,
            "level": self.ladder.level,
            "cycle": self.ladder.cycle,
        }
        logger.info(
            f"Label-flip ladder: sent {before:.0%} flipped -> "
            f"{'CAUGHT' if caught else 'missed'} ({self.caught_rule}) -> {event} -> "
            f"next round {self.ladder.fraction:.0%} "
            f"(level {self.ladder.level}/{self.ladder.n_levels - 1}, cycle {self.ladder.cycle})"
        )
        return record

    # ------------------------------------------------------------------
    def describe(self) -> str:
        pct = ", ".join(f"{f:.0%}" for f in self.ladder.levels())
        return (f"label_flip (symmetric y -> {self.n_classes - 1}-y) on clients "
                f"{self.poison_client_ids}; ladder {pct} then reset; "
                f"steps down when {self.caught_rule} poisoned client(s) are flagged")

    def state_dict(self) -> dict:
        return {"ladder": self.ladder.state_dict(),
                "poison_client_ids": list(self.poison_client_ids)}

    def load_state_dict(self, state: dict) -> None:
        if not state:
            return
        saved_ids = state.get("poison_client_ids")
        if saved_ids is not None and list(saved_ids) != self.poison_client_ids:
            logger.warning(
                f"attack.poison_client_ids changed since the last run "
                f"(saved={list(saved_ids)}, now={self.poison_client_ids}) — resuming the "
                f"ladder position against the NEW client set."
            )
        self.ladder.load_state_dict(state.get("ladder") or {})
        logger.info(
            f"Resumed label-flip ladder at {self.ladder.fraction:.0%} "
            f"(level {self.ladder.level}/{self.ladder.n_levels - 1}, "
            f"cycle {self.ladder.cycle})"
        )


def build_attacker(config: dict, n_clients: int, seed: int = 0) -> LabelFlipAttacker:
    """Build the attacker from the whole base config's ``attack:`` block.

    ``attack.type`` is validated rather than dispatched on: label flipping is the
    only attack this system implements, so an unrecognised value is a config
    error, not a request for a different attack.
    """
    attack = (config.get("attack") or {})
    atype = str(attack.get("type", "label_flip")).lower()
    if atype != "label_flip":
        raise ValueError(
            f"attack.type must be 'label_flip' (the only implemented attack), got "
            f"{atype!r}. Weight-space attack plans were removed — see data/label_flip.py."
        )
    attacker = LabelFlipAttacker(attack, n_clients=n_clients, seed=seed)
    logger.info(f"Attack: {attacker.describe()}")
    return attacker
